version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres_db'
    env_file:
      - .env
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./script/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  php:
   build:
     context: .docker
     dockerfile: Dockerfile
   image: php_engine_image
   container_name: php_engine
   volumes:
      - ./:/var/www/html
   environment:
     CONTAINER_ROLE: app
  redis:
     image: redis
     container_name: container_redis
     env_file:
      - .env
     ports:
       - "6379:6379"

  worker:
    image: app_mail
    container_name: worker
    restart: always
    pull_policy: never
    volumes:
      - ./app/src/:/var/www/html
    command: [ "php", "worker.php" ]